apiVersion: v1
kind: Service
metadata:
  name: {{ include "ghost.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ghost.name" . }}
    helm.sh/chart: {{ include "ghost.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 2368
      targetPort: 2368
      protocol: TCP
      name: ghost
  selector:
    app.kubernetes.io/name: {{ include "ghost.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
